root: true

extends:
  - pegasus
  - pegasus/browser
  - pegasus/react
  - prettier

rules:
  react/react-in-jsx-scope: off
  react/prop-types: off
  react-hooks/rules-of-hooks: error

parserOptions:
  project: true

overrides:
  - files:
      - '**/*.ts'
      - '**/*.tsx'
    extends:
      - pegasus/typescript
      - prettier
  - files:
      - 'docs/**/*.ts'
      - 'docs/**/*.tsx'
    parserOptions:
      project: true
      tsconfigRootDir: docs/

settings:
  react:
    version: detect
