root: true

extends:
  - pegasus
  - pegasus/browser
  - pegasus/react

rules:
  react/react-in-jsx-scope: off
  react/prop-types: off
  react-hooks/rules-of-hooks: error

parserOptions:
  project: tsconfig.json

overrides:
  - files:
      - '*.ts'
    extends:
      - pegasus/typescript

  - files:
      - scripts/*.js
      - .storybook/*.{js,cjs}
    extends:
      - pegasus/node

settings:
  react:
    version: detect
